[build]
  base = "Frontend/Proyecto-2-Archivos"
  command = "npm install && npm run build -- --configuration production"
  publish = "Frontend/Proyecto-2-Archivos/dist/Proyecto-2-Archivos/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
